services:
  ts-owncast:
    image: tailscale/tailscale:latest
    container_name: ts-owncast
    hostname: owncast
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_SERVE_CONFIG=/config/owncast.json
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - ${PWD}/ts-owncast/state:/var/lib/tailscale
      - ${PWD}/ts-owncast/config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
  owncast:
    image: owncast/owncast:${OWNCAST_VERSION:-0.1.3}
    container_name: owncast
    network_mode: service:ts-owncast
    depends_on:
      - ts-owncast
    volumes:
      - owncast-data:/app/data/
    restart: unless-stopped

volumes:
  owncast-data:
    driver: local
  ts-owncast:
    driver: local
