services:
  ts-mealie:
    image: tailscale/tailscale:latest
    container_name: ts-mealie
    hostname: mealie
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_SERVE_CONFIG=/config/mealie.json
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - ${PWD}/ts-mealie/state:/var/lib/tailscale
      - ${PWD}/ts-mealie/config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
  mealie:
    image: ghcr.io/mealie-recipes/mealie:${MEALIE_VERSION:-v1.10.2}
    container_name: mealie
    network_mode: service:ts-mealie
    depends_on:
      - ts-mealie
    volumes:
      - mealie-data:/app/data/
    environment:
      - ALLOW_SIGNUP=${SIGNUP:-false}
      - BASE_URL=${BASE_URL}
    restart: unless-stopped

volumes:
  mealie-data:
    driver: local
  ts-mealie:
    driver: local
